// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuD-z3_FSVRPB_iQD7CM3m36PToBV0kHE',
    appId: '1:324582703014:web:5616e68d95649f90c19967',
    messagingSenderId: '324582703014',
    projectId: 'bloogapp-9b529',
    authDomain: 'bloogapp-9b529.firebaseapp.com',
    storageBucket: 'bloogapp-9b529.appspot.com',
    measurementId: 'G-WHKH3T6M9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyXLzuQlxiYmB67Wia-zP-4fgLNlfaLxo',
    appId: '1:324582703014:android:8bf8a9eb66200ee2c19967',
    messagingSenderId: '324582703014',
    projectId: 'bloogapp-9b529',
    storageBucket: 'bloogapp-9b529.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqTiNkyvXvaPEF6f9pyVIfNqIQfq5kB-U',
    appId: '1:324582703014:ios:39a6c91a6d46bab2c19967',
    messagingSenderId: '324582703014',
    projectId: 'bloogapp-9b529',
    storageBucket: 'bloogapp-9b529.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );
}
